package model;
// Generated 25-sep-2019 22:29:28 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Asignaturas generated by hbm2java
 */
public class Asignaturas  implements java.io.Serializable {


     private int id;
     private Docente docente;
     private String descripcion;
     private String jornada;
     private String rowid;
     private Set gruposes = new HashSet(0);
     private Set pensums = new HashSet(0);
     private Set horarios = new HashSet(0);

    public Asignaturas() {
    }

	
    public Asignaturas(int id) {
        this.id = id;
    }
    public Asignaturas(int id, Docente docente, String descripcion, String jornada, String rowid, Set gruposes, Set pensums, Set horarios) {
       this.id = id;
       this.docente = docente;
       this.descripcion = descripcion;
       this.jornada = jornada;
       this.rowid = rowid;
       this.gruposes = gruposes;
       this.pensums = pensums;
       this.horarios = horarios;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Docente getDocente() {
        return this.docente;
    }
    
    public void setDocente(Docente docente) {
        this.docente = docente;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getJornada() {
        return this.jornada;
    }
    
    public void setJornada(String jornada) {
        this.jornada = jornada;
    }
    public String getRowid() {
        return this.rowid;
    }
    
    public void setRowid(String rowid) {
        this.rowid = rowid;
    }
    public Set getGruposes() {
        return this.gruposes;
    }
    
    public void setGruposes(Set gruposes) {
        this.gruposes = gruposes;
    }
    public Set getPensums() {
        return this.pensums;
    }
    
    public void setPensums(Set pensums) {
        this.pensums = pensums;
    }
    public Set getHorarios() {
        return this.horarios;
    }
    
    public void setHorarios(Set horarios) {
        this.horarios = horarios;
    }




}


