package model;
// Generated 25-sep-2019 22:29:28 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Docente generated by hbm2java
 */
public class Docente  implements java.io.Serializable {


     private int id;
     private String nombre;
     private String apellido;
     private Integer edad;
     private String email;
     private String rowid;
     private Set asignaturases = new HashSet(0);
     private Set usuarios = new HashSet(0);

    public Docente() {
    }

	
    public Docente(int id) {
        this.id = id;
    }
    public Docente(int id, String nombre, String apellido, Integer edad, String email, String rowid, Set asignaturases, Set usuarios) {
       this.id = id;
       this.nombre = nombre;
       this.apellido = apellido;
       this.edad = edad;
       this.email = email;
       this.rowid = rowid;
       this.asignaturases = asignaturases;
       this.usuarios = usuarios;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public Integer getEdad() {
        return this.edad;
    }
    
    public void setEdad(Integer edad) {
        this.edad = edad;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getRowid() {
        return this.rowid;
    }
    
    public void setRowid(String rowid) {
        this.rowid = rowid;
    }
    public Set getAsignaturases() {
        return this.asignaturases;
    }
    
    public void setAsignaturases(Set asignaturases) {
        this.asignaturases = asignaturases;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


