package model;
// Generated 25-sep-2019 22:29:28 by Hibernate Tools 4.3.1



/**
 * Facultad generated by hbm2java
 */
public class Facultad  implements java.io.Serializable {


     private int id;
     private Programa programa;
     private String descripcion;

    public Facultad() {
    }

	
    public Facultad(int id) {
        this.id = id;
    }
    public Facultad(int id, Programa programa, String descripcion) {
       this.id = id;
       this.programa = programa;
       this.descripcion = descripcion;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Programa getPrograma() {
        return this.programa;
    }
    
    public void setPrograma(Programa programa) {
        this.programa = programa;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


