package model;
// Generated 25-sep-2019 22:29:28 by Hibernate Tools 4.3.1



/**
 * Grupos generated by hbm2java
 */
public class Grupos  implements java.io.Serializable {


     private int id;
     private Asignaturas asignaturas;
     private String descripcion;

    public Grupos() {
    }

	
    public Grupos(int id) {
        this.id = id;
    }
    public Grupos(int id, Asignaturas asignaturas, String descripcion) {
       this.id = id;
       this.asignaturas = asignaturas;
       this.descripcion = descripcion;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Asignaturas getAsignaturas() {
        return this.asignaturas;
    }
    
    public void setAsignaturas(Asignaturas asignaturas) {
        this.asignaturas = asignaturas;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


