package model;
// Generated 25-sep-2019 22:29:28 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Horario generated by hbm2java
 */
public class Horario  implements java.io.Serializable {


     private int id;
     private Asignaturas asignaturas;
     private Date hora;
     private String dia;
     private String frecuencia;
     private String rowid;
     private Set recursoses = new HashSet(0);

    public Horario() {
    }

	
    public Horario(int id) {
        this.id = id;
    }
    public Horario(int id, Asignaturas asignaturas, Date hora, String dia, String frecuencia, String rowid, Set recursoses) {
       this.id = id;
       this.asignaturas = asignaturas;
       this.hora = hora;
       this.dia = dia;
       this.frecuencia = frecuencia;
       this.rowid = rowid;
       this.recursoses = recursoses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Asignaturas getAsignaturas() {
        return this.asignaturas;
    }
    
    public void setAsignaturas(Asignaturas asignaturas) {
        this.asignaturas = asignaturas;
    }
    public Date getHora() {
        return this.hora;
    }
    
    public void setHora(Date hora) {
        this.hora = hora;
    }
    public String getDia() {
        return this.dia;
    }
    
    public void setDia(String dia) {
        this.dia = dia;
    }
    public String getFrecuencia() {
        return this.frecuencia;
    }
    
    public void setFrecuencia(String frecuencia) {
        this.frecuencia = frecuencia;
    }
    public String getRowid() {
        return this.rowid;
    }
    
    public void setRowid(String rowid) {
        this.rowid = rowid;
    }
    public Set getRecursoses() {
        return this.recursoses;
    }
    
    public void setRecursoses(Set recursoses) {
        this.recursoses = recursoses;
    }




}


