package model;
// Generated 25-sep-2019 22:29:28 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pensum generated by hbm2java
 */
public class Pensum  implements java.io.Serializable {


     private int id;
     private Asignaturas asignaturas;
     private Date fecha;
     private String rowid;
     private Set semestres = new HashSet(0);
     private Set programas = new HashSet(0);

    public Pensum() {
    }

	
    public Pensum(int id) {
        this.id = id;
    }
    public Pensum(int id, Asignaturas asignaturas, Date fecha, String rowid, Set semestres, Set programas) {
       this.id = id;
       this.asignaturas = asignaturas;
       this.fecha = fecha;
       this.rowid = rowid;
       this.semestres = semestres;
       this.programas = programas;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Asignaturas getAsignaturas() {
        return this.asignaturas;
    }
    
    public void setAsignaturas(Asignaturas asignaturas) {
        this.asignaturas = asignaturas;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getRowid() {
        return this.rowid;
    }
    
    public void setRowid(String rowid) {
        this.rowid = rowid;
    }
    public Set getSemestres() {
        return this.semestres;
    }
    
    public void setSemestres(Set semestres) {
        this.semestres = semestres;
    }
    public Set getProgramas() {
        return this.programas;
    }
    
    public void setProgramas(Set programas) {
        this.programas = programas;
    }




}


