package model;
// Generated 25-sep-2019 22:29:28 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Programa generated by hbm2java
 */
public class Programa  implements java.io.Serializable {


     private int id;
     private Pensum pensum;
     private String descripcionPrograma;
     private Integer tipo;
     private String descripcionTipo;
     private String modalidad;
     private String duracion;
     private String titulo;
     private String registroCalificado;
     private String snies;
     private String director;
     private String email;
     private String rowid;
     private Set facultads = new HashSet(0);

    public Programa() {
    }

	
    public Programa(int id) {
        this.id = id;
    }
    public Programa(int id, Pensum pensum, String descripcionPrograma, Integer tipo, String descripcionTipo, String modalidad, String duracion, String titulo, String registroCalificado, String snies, String director, String email, String rowid, Set facultads) {
       this.id = id;
       this.pensum = pensum;
       this.descripcionPrograma = descripcionPrograma;
       this.tipo = tipo;
       this.descripcionTipo = descripcionTipo;
       this.modalidad = modalidad;
       this.duracion = duracion;
       this.titulo = titulo;
       this.registroCalificado = registroCalificado;
       this.snies = snies;
       this.director = director;
       this.email = email;
       this.rowid = rowid;
       this.facultads = facultads;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Pensum getPensum() {
        return this.pensum;
    }
    
    public void setPensum(Pensum pensum) {
        this.pensum = pensum;
    }
    public String getDescripcionPrograma() {
        return this.descripcionPrograma;
    }
    
    public void setDescripcionPrograma(String descripcionPrograma) {
        this.descripcionPrograma = descripcionPrograma;
    }
    public Integer getTipo() {
        return this.tipo;
    }
    
    public void setTipo(Integer tipo) {
        this.tipo = tipo;
    }
    public String getDescripcionTipo() {
        return this.descripcionTipo;
    }
    
    public void setDescripcionTipo(String descripcionTipo) {
        this.descripcionTipo = descripcionTipo;
    }
    public String getModalidad() {
        return this.modalidad;
    }
    
    public void setModalidad(String modalidad) {
        this.modalidad = modalidad;
    }
    public String getDuracion() {
        return this.duracion;
    }
    
    public void setDuracion(String duracion) {
        this.duracion = duracion;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getRegistroCalificado() {
        return this.registroCalificado;
    }
    
    public void setRegistroCalificado(String registroCalificado) {
        this.registroCalificado = registroCalificado;
    }
    public String getSnies() {
        return this.snies;
    }
    
    public void setSnies(String snies) {
        this.snies = snies;
    }
    public String getDirector() {
        return this.director;
    }
    
    public void setDirector(String director) {
        this.director = director;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getRowid() {
        return this.rowid;
    }
    
    public void setRowid(String rowid) {
        this.rowid = rowid;
    }
    public Set getFacultads() {
        return this.facultads;
    }
    
    public void setFacultads(Set facultads) {
        this.facultads = facultads;
    }




}


