package model;
// Generated 25-sep-2019 22:29:28 by Hibernate Tools 4.3.1



/**
 * Recursos generated by hbm2java
 */
public class Recursos  implements java.io.Serializable {


     private int id;
     private Horario horario;
     private Sede sede;
     private Integer tipo;
     private String descripcionTipo;
     private String nro;
     private Integer disponibilidad;

    public Recursos() {
    }

	
    public Recursos(int id) {
        this.id = id;
    }
    public Recursos(int id, Horario horario, Sede sede, Integer tipo, String descripcionTipo, String nro, Integer disponibilidad) {
       this.id = id;
       this.horario = horario;
       this.sede = sede;
       this.tipo = tipo;
       this.descripcionTipo = descripcionTipo;
       this.nro = nro;
       this.disponibilidad = disponibilidad;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Horario getHorario() {
        return this.horario;
    }
    
    public void setHorario(Horario horario) {
        this.horario = horario;
    }
    public Sede getSede() {
        return this.sede;
    }
    
    public void setSede(Sede sede) {
        this.sede = sede;
    }
    public Integer getTipo() {
        return this.tipo;
    }
    
    public void setTipo(Integer tipo) {
        this.tipo = tipo;
    }
    public String getDescripcionTipo() {
        return this.descripcionTipo;
    }
    
    public void setDescripcionTipo(String descripcionTipo) {
        this.descripcionTipo = descripcionTipo;
    }
    public String getNro() {
        return this.nro;
    }
    
    public void setNro(String nro) {
        this.nro = nro;
    }
    public Integer getDisponibilidad() {
        return this.disponibilidad;
    }
    
    public void setDisponibilidad(Integer disponibilidad) {
        this.disponibilidad = disponibilidad;
    }




}


