package model;
// Generated 25-sep-2019 22:29:28 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Sede generated by hbm2java
 */
public class Sede  implements java.io.Serializable {


     private int id;
     private String ubicacion;
     private String rowid;
     private Set recursoses = new HashSet(0);

    public Sede() {
    }

	
    public Sede(int id) {
        this.id = id;
    }
    public Sede(int id, String ubicacion, String rowid, Set recursoses) {
       this.id = id;
       this.ubicacion = ubicacion;
       this.rowid = rowid;
       this.recursoses = recursoses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getUbicacion() {
        return this.ubicacion;
    }
    
    public void setUbicacion(String ubicacion) {
        this.ubicacion = ubicacion;
    }
    public String getRowid() {
        return this.rowid;
    }
    
    public void setRowid(String rowid) {
        this.rowid = rowid;
    }
    public Set getRecursoses() {
        return this.recursoses;
    }
    
    public void setRecursoses(Set recursoses) {
        this.recursoses = recursoses;
    }




}


