package model;
// Generated 25-sep-2019 22:29:28 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Semestre generated by hbm2java
 */
public class Semestre  implements java.io.Serializable {


     private int id;
     private Pensum pensum;
     private Integer nroSemestre;
     private Date fechaInicio;
     private Date fechaFinal;

    public Semestre() {
    }

	
    public Semestre(int id) {
        this.id = id;
    }
    public Semestre(int id, Pensum pensum, Integer nroSemestre, Date fechaInicio, Date fechaFinal) {
       this.id = id;
       this.pensum = pensum;
       this.nroSemestre = nroSemestre;
       this.fechaInicio = fechaInicio;
       this.fechaFinal = fechaFinal;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Pensum getPensum() {
        return this.pensum;
    }
    
    public void setPensum(Pensum pensum) {
        this.pensum = pensum;
    }
    public Integer getNroSemestre() {
        return this.nroSemestre;
    }
    
    public void setNroSemestre(Integer nroSemestre) {
        this.nroSemestre = nroSemestre;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFinal() {
        return this.fechaFinal;
    }
    
    public void setFechaFinal(Date fechaFinal) {
        this.fechaFinal = fechaFinal;
    }




}


